### PR TITLE
Correct vendor get op code and vendor op code creation

### PR DESCRIPTION
**Pull request by ball-hayden**
This PR fixes two issues related to handling of vendor op codes.

Firstly, it corrects the ordering of `MeshParserUtils#getOpCode` and adds a JUnit test for this method.

Whilst writing the JUnit test, I noted that `createVendorOpCode` didn't behave as I would expect it to. It previously expected `0xC0` to have already been added to the opCode, and for the opCode to have already been shifted by 16 bits. `I have modified it such that it will take the vendor's op code and company ID, and convert them into the correct 3-byte opCode. This is also unit tested.

These changes also fix two existing failing tests: `AccessLayerTests#create_custom_access_message_isCorrect` and ``AccessLayerTests#create_custom_access_message_isCorrect1`.

I note that there are a number of other failing tests - might it be worth setting up GitHub Actions to run the limited unit tests for this project?

### CODE REVIEW

**Comment by roshanrajaratnam** [comment]
@ball-hayden Thanks for your contribution, could you base it to the dev branch please?
I took a quick look at it and it seems to be fine. Not sure how I got around this issue. About the tests, there are some that are failing and these were mostly some are outdated and has to be changed to based on changes made as we progressed and were manually tested.

Currently this is in my backlog and I'll start lookin to it soon.

**Comment by ball-hayden** [comment]
Thanks @roshanrajaratnam - rebased as requested.

**Comment by roshanrajaratnam** [comment]
@ball-hayden I meant to send the pull request to the dev branch. Sorry for the inconvenience.

**Comment by ball-hayden** [comment]
Argh. Sorry - my mistake.

**Review by roshanrajaratnam — COMMENTED** [review]
IMHO I feel that it's nice to have the 3-octet opcode prepared in the VendorModelMessageAcked and VendorModelMessageUnacked, but at the same time this is a welcoming change that makes the opcode creation testable.

**Review by roshanrajaratnam — COMMENTED** [review]
This goes inline with the previous commit and fixes the incorrect `getOpCode(final byte[] accessPayload, final int opCodeCount)`

**Pull request merged**
