### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheBosZ**
Removed references to jcenter and fixed spelling

### CODE REVIEW

**Comment by TheBosZ** [comment]
I think I'm okay with signing the CLA for the company that I work for... :)

**Comment by philips77** [comment]
I don't know. I kinda got use to those typos. It's hard to read now with the correct spelling. 
Also, please print the CLA in 3 copies, send it to us with a motivation letter why the PR in the first place. We will kindly ~reject~review it in 2 weeks. 

Thank you.

Sincerely, 
The company you work for.

**Comment by TheBosZ** [comment]
> I don't know. I kinda got use to those typos. It's hard to read now with the correct spelling.

Oh! I didn't realize that those were **structural** misspellings!

**Comment by roshanrajaratnam** [comment]
After much consideration.

**Pull request merged**
