### PR TITLE
Feat/sequence number

### PR DESCRIPTION
**Pull request by DomiR**
@roshanrajaratnam Hey, here is the PR. I don't know if this is the best design, as we pass the callbacks pretty far down the chain, but we somehow need to persist the incremented sequence number, otherwise it will be 0 on every app start.

If this was fixed somehow differently, please point me to it and close the PR 😄

### CODE REVIEW

**Comment by roshanrajaratnam** [comment]
@DomiR Thanks for this, i'll get back to you on this soon.

**Comment by roshanrajaratnam** [comment]
@DomiR Ok this is pretty strange. I provisioned a node killed the app and restarted and checked the sequence number and its not 0. Could you confirm this?

The thing is that the provisioner is persisted when receiving a status message. may be I should save it right after sending a message as well...

**Comment by DomiR** [comment]
Thanks for testing it! In the previous version I was using, it was not beeing stored correctly, but now it is. When sending unack messages, I think we still need to store the incremented sequence number.

**Comment by roshanrajaratnam** [comment]
Agreed. I will cherry pick from your PR! because I have internally fixed the 2nd fix you have made regarding the k2output. It's ideally a Network property. All we need is the network key used in the message based on the NID. Thanks again for your PR!

**Comment by DomiR** [comment]
Okay perfect, just cherry pick the things you like 😉

**Pull request closed without merging**
