### PR TITLE
Add callback to handle missing mesh node

### PR DESCRIPTION
**Pull request by ball-hayden**
For our application, we have a need for different instances of the application to be able to join an existing network. The network and application key(s) can be shared out of band, but on joining we receive no messages from nodes.

This PR allows an application to respond to messages which have been received from unknown nodes. The implementing application can then chose to create a new `ProvisionedMeshNode` object (see https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/pull/366), then continue to process the received message.

### CODE REVIEW

**Comment by ball-hayden** [comment]
Interestingly, the iOS library seems to manage to deliver messages from unknown nodes to the application without an additional callback - is there a way that the Android library could do the same?

**Review by roshanrajaratnam — COMMENTED** [review]
ops, check below!

**Review by roshanrajaratnam — CHANGES_REQUESTED** [review]
@ball-hayden There could be a slight issue here with callback. As you could see on the `BaseMeshMessageHandler.java` class , the while loop will check for the possible `ivIndexes` such as current `ivIndex` and also the `ivIndex - 1`.  We assume that the de-obfuscation fails if the node is null and continue de-obfuscating until we find a `node` that may exist in the network. So this would cause the callback to be invoked multiple times for the same message and for each possible 'ivIndex' while looping through the list of Network Keys. I would suggest moving the `src` and `node` out of the while loop and the callback should be placed at the end and outside of the while loop with a check to verify the maximum IV Index is reached and that the node is null.

If you have a test setup for this could you verify as well?

**Comment by ball-hayden** [comment]
You're quite right @roshanrajaratnam. We'll have a look into this next week.

We have been using this in its current form successfully, and I'll give this a go after any changes.

I don't suppose you have more knowledge of how the iOS library manages to achieve message processing for unknown nodes without such a callback?

**Comment by roshanrajaratnam** [comment]
Ah right. Give it a go and let me know if possible. I'm off until new year but I'll try to take a look if I get a chance next week to see about the iOS Lib.

**Comment by ball-hayden** [comment]
^ I've started to move some things around, but I don't have much confidence in that.
I'll try and find some time this week to write up some tests for `parseMeshPduNotifications`.

**Pull request closed without merging**
