### PR TITLE
Fix #469 create group with multiple ranges

### LINKED ISSUE #469: Add group is broken if provisioner have more than 1 group range
---

**Describe the bug**
If a provisioner has more than 1 groups range the add Group function will always fail.

**To Reproduce**
In mesh app:
1. Go to provisioner
2. Add new group range, e.g E000-EFFF
3. Try and add a new group to any of the ranges, it will always fail

**Expected behavior**
Group should work in either range.

Problem relies here, if the group is outside any of the ranges create group will fail.

https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/e03b1eba6cf4d7bb41b1fa36d3ce8055e8df4208/mesh/src/main/java/no/nordicsemi/android/mesh/MeshNetwork.java#L434

### PR DESCRIPTION
**Pull request by Rawa**
Fixes issue #469

### CODE REVIEW

**Comment by Rawa** [comment]
I've not tested it yet, needs testing in Nrf Mesh app before accepting.

**Comment by philips77** [comment]
Looks good to me. But with merging I'll wait for @roshanrajaratnam. He should be back next week.
Thank you again for catching the issue and great fix!

**Comment by Rawa** [comment]
I was able to spend some more time on this and tested in the nRF Mesh app. Patch works as intended and allows for creation of group in both ranges.

**Comment by philips77** [comment]
That's what I thought. The code looked solid. Once again, thanks for contributing!

**Pull request merged**
