### PR TITLE
fix incorrect percentage

### PR DESCRIPTION
**Pull request by Coral-CW**
Fix incorrect percentage bytes

### CODE REVIEW

**Comment by philips77** [comment]
Good catch, here's the spec for Percentage8. Also, 0xFF is unknown value, which also should be implemented. Perhaps nullable Float?
image

**Comment by philips77** [comment]
https://www.bluetooth.org/docman/handlers/DownloadDoc.ashx?doc_id=539729

**Comment by Coral-CW** [comment]
Okay, sorry for careless

**Review by roshanrajaratnam — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
