### PR TITLE
Feature/implement light lightness, light ctl and light hsl  messages

### PR DESCRIPTION
**Pull request by DomiR**

### CODE REVIEW

**Comment by roshanrajaratnam** [comment]
Really appreciate this @DomiR. I noticed that the DefaultNoOperationState does not parse the status messages. Did you forget to add it after the new changes? if so I can add it myself :)

**Comment by DomiR** [comment]
Hey @roshanrajaratnam, you are absolutely right! I've added the missing code. Please cherry pick or rebase however you please. I also switched over the optcodes to "unsigned" ints, as they are stored everywhere as ints and logged as Integer.toHexstring(). If you like me to change it back, just let me know.

**Comment by roshanrajaratnam** [comment]
Thanks @DomiR, this is perfectly fine. Something I should have fixed long time ago! :)

**Comment by DomiR** [comment]
I‘m still testing this today and will push my last fixes this evening...

**Comment by DomiR** [comment]
I've tested lightness and ctl which are working. @roshanrajaratnam maybe you can take another look at the status parsing and the message assembly but I think it should be fine.

**Comment by roshanrajaratnam** [comment]
@DomiR Sure I will take a look at this and keep you posted. Thanks for this!

**Comment by DomiR** [comment]
Hmm, I've noticed that using node.getSequenceNum() for the TransitionID won't work, as we need to increment it when sending unacknowledged messages or when an acknowledgement is dropped, but the sequence number is currently only updated, when a response message was received.

I'm going to add the tID to all messages that need it and have a deprecated method, that uses the sequence number...

**Comment by DomiR** [comment]
closed in favor of #100

**Pull request closed without merging**
